# Re-run model selection for MG and SP only, using the updated pipeline
# (ENSO/IOD/PDO re-inclusion, searched d/D, bootstrap forecast intervals).
#
# This does NOT read or write sarimax/results/concluded_states.csv -- it uses
# a throwaway checkpoint file in a temp directory instead, so the real
# checkpoint (which lists all 26 states as done) is left untouched.
#
# It DOES overwrite the real per-state result files for MG and SP:
#   sarimax/results/metrics/metrics_all_formulas_MG.csv
#   sarimax/results/metrics/mean_wis_best_model_MG.csv
#   (and the same two for SP)
# sarimax/results/metrics/best_wis_all_states.csv is NOT touched here --
# see the note printed at the end for how to refresh it.
#
# Run from the project root:
#   Rscript sarimax/run_mg_sp_test.R

states_to_run <- c("MG", "SP")

# ---- Load the run_model_selection() function from model_sel.r without
# ---- executing its bottom loop (which would process all 26 states and
# ---- rewrite best_wis_all_states.csv).
model_sel_lines <- readLines("sarimax/src/model_sel.r")
cutoff <- grep("^states <- c\\(", model_sel_lines)[1]
if (is.na(cutoff)) {
  stop("Could not find the 'states <- c(' marker in sarimax/src/model_sel.r ",
       "-- the file may have changed shape; update this script's cutoff logic.")
}
source(textConnection(model_sel_lines[seq_len(cutoff - 1)]))

# ---- Build a concluded_states table that excludes only the states we're
# ---- testing, so run_model_selection() doesn't skip them, and point its
# ---- internal checkpoint write at a scratch file instead of the real one.
all_states <- c("AC", "AL", "AM", "AP", "BA", "CE", "DF", "GO", "MA",
                "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ",
                "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO")

scratch_checkpoint <- file.path(tempdir(), "concluded_states_test.csv")
concluded_subset <- data.frame(
  state = setdiff(all_states, states_to_run),
  stringsAsFactors = FALSE
)

results <- lapply(states_to_run, function(st) {
  message("==== Running ", st, " ====")
  run_model_selection(
    state                  = st,
    concluded_states       = concluded_subset,
    concluded_states_path  = scratch_checkpoint
  )
})
names(results) <- states_to_run

cat("\n==== Done ====\n")
for (st in states_to_run) {
  cat("\n---", st, "best formula/order ---\n")
  print(results[[st]]$best_formula)
  print(results[[st]]$best_order)
  cat("\n", st, "final per-fold metrics (incl. coverage_*):\n")
  print(results[[st]]$final_metrics)
}

cat("\nUpdated files:\n")
for (st in states_to_run) {
  cat(" - sarimax/results/metrics/metrics_all_formulas_", st, ".csv\n", sep = "")
  cat(" - sarimax/results/metrics/mean_wis_best_model_", st, ".csv\n", sep = "")
}
cat("\nNOTE: best_wis_all_states.csv was NOT regenerated by this script.\n")
cat("Once you're happy with MG/SP, rebuild it with:\n")
cat('  library(readr); library(dplyr)\n')
cat('  best_wis_df <- bind_rows(lapply(c("AC","AL","AM","AP","BA","CE","DF","GO","MA",\n')
cat('    "MG","MS","MT","PA","PB","PE","PI","PR","RJ","RN","RO","RR","RS","SC","SE","SP","TO"),\n')
cat('    function(st) { d <- read_csv(paste0("sarimax/results/metrics/metrics_all_formulas_", st, ".csv"), show_col_types = FALSE); d[1,] |> mutate(state = st, .before = 1) }))\n')
cat('  write_csv(best_wis_df, "sarimax/results/metrics/best_wis_all_states.csv")\n')
